apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pipeline.openshift.io/started-by: kube:admin
  labels:
    app: hello
    tekton.dev/pipeline: build-images
  name: build-images-run
  namespace: demo
spec:
  pipelineRef:
    name: build-images
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: demo-pvc