#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM python:alpine AS build

RUN pip install --no-cache-dir httpx starlette sse_starlette uvicorn && \
    python -c "import site; print(site.getsitepackages()[0])" > /tmp/python_site_packages.txt && \
    SITE_PACKAGES=$(cat /tmp/python_site_packages.txt) && \
    cp -r $SITE_PACKAGES /tmp/site-packages

FROM python:alpine AS run

RUN adduser -S fritz -G root

# Copy site-packages dynamically based on Python version
COPY --from=build /tmp/python_site_packages.txt /tmp/
COPY --from=build /tmp/site-packages /tmp/site-packages-source
RUN PYTHON_SITE_PACKAGES=$(cat /tmp/python_site_packages.txt) && \
    mkdir -p $(dirname $PYTHON_SITE_PACKAGES) && \
    cp -r /tmp/site-packages-source/* $PYTHON_SITE_PACKAGES/ && \
    rm -rf /tmp/site-packages-source /tmp/python_site_packages.txt

USER fritz
COPY --chown=fritz:root python /home/fritz/python
COPY --chown=fritz:root static /home/fritz/static

EXPOSE 8080
WORKDIR /home/fritz
ENTRYPOINT ["python", "python/main.py"]
