apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo #Change as per required
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/backend
    repoURL: https://github.com/arslankhanali/demo_multiarch
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true