name: Build and Push Multi-Arch Podman Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Login to Quay.io
        run: podman login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push backend image
        run: |
          cd skupper-app/backend
          podman buildx build --platform linux/amd64 --file Containerfile --tag quay.io/arslankhanali/skupper-backend:x86_64 --push .
          podman buildx build --platform linux/ppc64le --file Containerfile --tag quay.io/arslankhanali/skupper-backend:ppc64le --push .

      - name: Build and push frontend image
        run: |
          cd skupper-app/frontend
          podman buildx build --platform linux/amd64 --file Containerfile --tag quay.io/arslankhanali/skupper-frontend:x86_64 --push .
          podman buildx build --platform linux/ppc64le --file Containerfile --tag quay.io/arslankhanali/skupper-frontend:ppc64le --push .

      - name: Create and push multi-arch manifests for backend
        run: |
          podman manifest create mylist-back
          podman manifest add mylist-back quay.io/arslankhanali/skupper-backend:x86_64
          podman manifest add mylist-back quay.io/arslankhanali/skupper-backend:ppc64le
          podman manifest push --creds ${{ secrets.QUAY_USERNAME }}:${{ secrets.QUAY_PASSWORD }} mylist-back quay.io/arslankhanali/skupper-backend:github

      - name: Create and push multi-arch manifests for frontend
        run: |
          podman manifest create mylist-front
          podman manifest add mylist-front quay.io/arslankhanali/skupper-frontend:x86_64
          podman manifest add mylist-front quay.io/arslankhanali/skupper-frontend:ppc64le
          podman manifest push --creds ${{ secrets.QUAY_USERNAME }}:${{ secrets.QUAY_PASSWORD }} mylist-front quay.io/arslankhanali/skupper-frontend:github

      - name: Logout from Quay.io
        run: podman logout quay.io
